### ISSUE TITLE
Unresponsive register modal in demo

### ISSUE THREAD

**Issue by tracktorr1** [jimmybrancaccio/cmangos-starter-website#1]
The "register" button on the modal either does not send a POST or does not appear to be received by the register.php script for parsing. Subsequently, the same problem was encountered when pulling and testing locally with PHP version 8.1.10. I'm not experienced with web development and haven't been able to figure out why this behavior is occurring.

**Comment by jimmybrancaccio** [comment]
As noted in Discord this is because the Submit button is outside the ending `</form>` tag. I will look into getting this fixed in the repo ASAP! Thanks for reporting! 😄
